[connections.snowflake]
account= "TQWEKGS-WW35913" 
user = "ASHWINI24"
password = "Welcome@25"
role = "SYSADMIN"
warehouse = "COMPUTE_EH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
